# .github/workflows/deploy.yml

name: Deploy Yangkar Website

on:
    push:
        branches:
            - main # Trigger this workflow on every push to the main branch

jobs:
    deploy-backend:
        name: Deploy Backend API
        runs-on: ubuntu-latest
        environment: production # Uses secrets from your 'production' environment

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: "10.13.1" # Version from your package.json

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # A stable, modern Node.js version
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Deploy to Backend Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.BACKEND_SSH_HOST }}
                  username: ${{ secrets.BACKEND_SSH_USERNAME }}
                  password: ${{ secrets.BACKEND_SSH_PASSWORD }}
                  script: |
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

                      cd /home/yangkarbhoeche-api/htdocs/api.yangkarbhoeche.com/YangkarSvelteKit

                      # First pull the latest code
                      git pull origin main

                      # Then install dependencies
                      pnpm install

                      # Run migrations with the latest schema
                      pnpm --filter backend exec prisma migrate deploy

                      # Now generate Prisma client with the updated schema
                      pnpm --filter backend exec prisma generate

                      # Finally restart the service
                      pm2 restart backend

    deploy-frontend:
        name: Deploy Frontend App
        runs-on: ubuntu-latest
        environment: production # Uses secrets from your 'production' environment
        needs: deploy-backend # This job will wait for the backend deployment to succeed

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: "10.13.1" # Version from your package.json

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Deploy and build on the server directly
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.FRONTEND_SSH_HOST }}
                  username: ${{ secrets.FRONTEND_SSH_USERNAME }}
                  password: ${{ secrets.FRONTEND_SSH_PASSWORD }}
                  script: |
                      export NVM_DIR="$HOME/.nvm"
                      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

                      cd /home/yangkarbhoeche/htdocs/yangkarbhoeche.com/YangkarSvelteKit

                      # First pull the latest code
                      git pull origin main

                      # Install dependencies
                      pnpm install

                      # Build the frontend app directly on the server
                      pnpm --filter frontend build

                      # Restart the service
                      pm2 restart frontend
